menu:
  Nefelibata: ../
  Blog: /
  Gallery: ../gallery
  Github: https://github.com/kpl0111
  About: ../about

excerpt_link: Read More

favicon:
  url: /images/favicon.png

# MathJax Support
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML